### ISSUE TITLE
Seems to have no effect on PyCharm Community Edition 2016.3.2 Build #PC-163.10154.50

### ISSUE THREAD

**Issue by JamesGalt** [kropp/intellij-makefile#10]
Hi,
first let me thank you for the work.
i tried to install the plugin but it seems to have no effect on 
`PyCharm Community Edition 2016.3.2 Build #PC-163.10154.50`
any idea to make it working?
Thanks
James

**Comment by kropp** [comment]
Thank you @JamesGalt !
I tried latest version of plugin with PyCharm Community and it works for me.
What can possibly happen:
1. By default plugin handles files with `*.mk` extension or with name `Makefile` (Does it show GNU Head icon for the file? Can you assign file association manually?)
2. Parsing problem may happen near the beginning of the file so the rest is not parsed (Please send me example in this case)
3. By default there is almost no custom colors, you can set up those in Settings - Editor - Makefile (please check if you see anything there)
