### ISSUE TITLE
$(MAKE) -f <file>/$(MAKE) -C <directory> should be navigateable, like include

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#101]
Ctrl-clicking on `make -C <dir>`, `$(MAKE) --directory=<dir>`, `make -f <file>` etc should open the Makefile (in the target directory), like Ctrl-clicking `include <file>` opens the target file.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
