### ISSUE TITLE
Support for 192.0+ builds

### ISSUE THREAD

**Issue by stdedos** [kropp/intellij-makefile#102]
Is the plugin supported in `2019.x` versions? It seems that Settings --> Plugin does not find it :confused:

**Comment by kropp** [comment]
It works for me in IntelliJ IDEA and CLion 2019.2 EAP builds.
What IDE are you using?

**Comment by stdedos** [comment]
PyCharm, `Build #PC-192.4205.50, built on May 27, 2019`

Or the next one, if there is one

**Comment by stdedos** [comment]
It seems that after updating to `Build #PC-192.4787.5, built on June 4, 2019`, it works! :smile:
