### ISSUE TITLE
No syntax highlighting in JetBrains Goland

### ISSUE THREAD

**Issue by OscarHanzely** [kropp/intellij-makefile#103]
When plugin is used in Intellij Goland no syntax highlighting is available. 
![image](https://user-images.githubusercontent.com/39314151/60744133-c9d67600-9f31-11e9-9b5e-b6e1fbe0963e.png)
Golang 2019.1.3 build #GO-191.74.79.32 from May 29, 2019

**Comment by sergeyklay** [comment]
The same  
![image](https://user-images.githubusercontent.com/1256298/61996355-2f82d180-b09c-11e9-8f52-6eea77529c51.png)

GoLand 2019.2
Build #GO-192.5728.103, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.0-5-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 20
Registry: run.processes.with.pty=TRUE, ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: name.kropp.intellij.makefile, BashSupport, org.toml.lang

Plugin version: 1.6.1

**Comment by kropp** [comment]
As you may see keywords and variable contents are highlighted in these screenshots. So Makefile syntax highlighting does work. What doesn't is the shell language injection, see #90

**Comment by sergeyklay** [comment]
@kropp How about `.PHONY` then? I'm pretty sure there are more unhighlighted keywords. Also why targets are highlighted just like a regular text? Finally, why `$( )` isn't highlighted?
