### ISSUE TITLE
Register more file patterns

### ISSUE THREAD

**Issue by jansenm** [kropp/intellij-makefile#11]
Hi

Thanks for this. I loved the moment i could get rid of that textmate workaround :)

Please associate more patterns with this plugin (https://www.gnu.org/software/make/manual/make.html#Makefile-Names)
- GNUMakefile
- makefile

And just for me :)

- Makefile.* (eg. Makefile.local)

Mike

**Comment by kropp** [comment]
I've added GNUmakefile (please note lower-case m) and makefile
GNUMakefile (with upper-case M) is not recognized by GNU Make 4.1 on Ubuntu

Where do you use Makefile.*? Which tools support such names? If it is rare case could you please use 'Associate with File Type' context action?

**Comment by jansenm** [comment]
Its not that rare. If you search for Makefile.local on eg. google 

https://www.google.de/search?q=Makefile.local&ie=utf-8&oe=utf-8&gws_rd=cr&ei=KRV6WNrRC4iIgAbqiKC4BQ#q=%22Makefile.local%22

You will get lots of results. I tried to search on github but it does not really support this use case. Or i am to stupid to understand how :). I then out of curiosity checked how vim recognized makefiles

/usr/share/vim/vim74/filetype.vim

" Makefile
au BufNewFile,BufRead *[mM]akefile,*.mk,*.mak,*.dsp setf make

" Makefile
au BufNewFile,BufRead [mM]akefile*              call s:StarSetf('make')

But its you decision. Thx.

**Comment by kropp** [comment]
Ok, I agree Makefile.* is quite popular. Added it.
`*.mak` and `*.dsp` are Makefile variants for NMAKE. Though it still seems to be supported by Microsoft, its syntax differ and plugin won't support it without additional changes.
