### ISSUE TITLE
Create a EAP channel for the plugin

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#110]
It's possible to create a beta/EAP channels for Intellij plugins, separate from stable release.

Seeing all the awesome recent fixes, I'd love to try them out. Plus, I have a really complicated Makefile project and would love to test on it. Current stable version barely provides any functionality to me because of #107. 

I believe I could discover a lot more corner cases if the parser worked on more than 10% of my Makefiles and quickly report any problems back.

**Comment by singalen** [comment]
Thanks for publishing 2.0! Now this issue is not needed that much, but it's still very desirable, with all the awesome fixes going on.
Would especially love to see the robustness fixes.

**Comment by singalen** [comment]
Yay! Awesome fixes! Release please!

**Comment by kropp** [comment]
Version 2.9 is now available in Preview channel.
https://plugins.jetbrains.com/plugin/9333-makefile-support/update/81801

**Comment by singalen** [comment]
FTYI, preview channel of the plugin to configure in Settings - Plugins: https://plugins.jetbrains.com/plugins/preview/9333
