### ISSUE TITLE
cannot run 2.0 version on goland

### ISSUE THREAD

**Issue by playniuniu** [kropp/intellij-makefile#112]
Error message 

Plugin "Makefile support" defines no module dependencies (supported only in IntelliJ IDEA).

**Comment by rebrendov** [comment]
This is the same as #111.

**Comment by andisolo** [comment]
same in clion

**Comment by Tafkas** [comment]
same in PyCharm Professional

**Comment by kropp** [comment]
Fixed in 2.0.1
