### ISSUE TITLE
$(patsubst %,build-module-%,$(ALL_MODULES)) not supported

### ISSUE THREAD

**Issue by sonersivri** [kropp/intellij-makefile#116]

**Comment by singalen** [comment]
Can you add more detail? If I were the author, I wouldn't be able to understand what is the problem here.
What makefile you have, what is the expected behavior, what are you getting instead?

**Comment by singalen** [comment]
Can you add more detail? If I were the author, I wouldn't be able to understand what is the problem here.
What makefile you have, what is the expected behavior, what are you getting instead?

**Comment by enerjazzer** [comment]
It's likely a duplicate of https://github.com/kropp/intellij-makefile/issues/115

**Comment by sonersivri** [comment]
commit fixed this issue thanks
