### ISSUE TITLE
ifdef not properly recognized

### ISSUE THREAD

**Issue by Fleshgrinder** [kropp/intellij-makefile#12]
```
target:
ifdef VARIABLE_NAME
	cmd
else
	else-cmd
endif
```

The `ifdef` will not be recognized as keyword and the subsequent line’s tab indention is marked as error with the message:

> ':' or identifier expected, got ''

**Comment by Fleshgrinder** [comment]
Thanks for the fast fix. 👍

**Comment by edpop** [comment]
Is that fix includes in v1.0? There is still an error:
`
<include>, <topconditional>, comment, define, else, endif, export, identifier, override, private, undefine or vpath expected, got ''
` in

```make
ifeq ($(CONDITION))
	DO1
else
	DO2
endif

all: some
```

before `DO1`

**Comment by kropp** [comment]
I've just discovered a case where it fails. Will fix ASAP, thanks!

**Comment by ags799** [comment]
Was this fixed? For some code

```make
ifdef key
	VAR ?= 1
endif
```

I get @edpop's error

    <include>, <topconditional>, comment, define, else, endif, export, identifier, override, private, undefine or vpath expected, got ''

Makefile plugin v1.2.
Gogland (1.0 Preview) 1.0 EAP
Build #GO-172.3757.2, built on August 1, 2017
Gogland EAP User
Expiration date: October 30, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by ags799** [comment]
@edpop I'm still working on the fix, and it's clear that I won't be finishing it anytime soon. But it does seem that editing your `Makefile` could solve the problem. Instead of

```make
ifdef key
        VAR ?= 1
endif
```
do

```make
ifdef key
VAR ?= 1
endif
```

**Comment by sssilver** [comment]
Shall we reopen this issue? Why is it closed? Observing it on the latest version.
