### ISSUE TITLE
Comment within a recipe should be passed to a shell

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#121]
> [Comments within a recipe are passed to the shell, just as with any other recipe text. The shell decides how to interpret it](https://www.gnu.org/software/make/manual/html_node/Makefile-Contents.html: ).

The tail of this recipe is interpreted as if it has a `make` comment, while it's a recipe body, and thus should be a shell comment:
```
bar:
	if [ -f foo ]; then \
	  echo "##hello, sir!"; \
	fi
```

Note that `\` at the end of the line is still `make`'s syntax.

**Comment by singalen** [comment]
Another instance of the same problem (I think): a comment in a target inside of `if` breaks the syntax.

```
target:
    ls
ifeq ($(A),b)
    # here be the error
    ls 
endif
    ls
```

Maybe it's a different problem, because now the body of `ifeq` is not parsed as a shell commands.

**Comment by singalen** [comment]
Looks like this is fixed in the EAP version?

**Comment by kropp** [comment]
Yep, added a test for completeness.
