### ISSUE TITLE
Target-specific variable syntax error

### ISSUE THREAD

**Issue by marek-martin** [kropp/intellij-makefile#13]
Hey,

Thanks for the plugin! Much appreciated!
One minor issue though. Target-specific variable assignment shows syntax error. 
In this Makefile:
```
test: export PYTHONPATH=$(PACKAGE_DIR)
test: testbuild build
	@py.test -vv --basetemp=$(TEST_DATA_DIR) $(TEST_CODE_DIR)
```
The '=' on the first line causes syntax error:
';', EOL, comment, identifier, split or '|' expected, got '='
![screenshot_2017-01-18_10-55-47](https://cloud.githubusercontent.com/assets/4658910/22057377/124a3c70-dd6d-11e6-8cef-7071639eb4c6.png)

**Comment by kropp** [comment]
Thanks!
Sorry, I don't quite understand what does this Makefile do?

**Comment by jansenm** [comment]
I think this should show it clearly: 

```

# This set VARIABLE to "foo" for the duration of handling test-bar
test-foo: export VARIABLE=foo
# The above target are not actually a executable target. Without the next line you would get.
# make: *** No rule to make target 'test-foo', needed by 'all'.  Stop.
test-foo:
	@echo "$$VARIABLE"

# This set VARIABLE to "bar" for the duration of handling test-bar
test-bar: export VARIABLE=bar
test-bar:
	@echo "$$VARIABLE"

all: test-foo test-bar
```

Execute `make all`

And here is the documentation:

https://www.gnu.org/software/make/manual/html_node/Target_002dspecific.html

**Comment by kropp** [comment]
Thanks for an example!
Now, I got it.
