### ISSUE TITLE
Can't resolve next target when prerequisites generated by function call

### ISSUE THREAD

**Issue by ylevin** [kropp/intellij-makefile#131]
In that case plugin says "Unresolved prerequisite" and it can't resolve that `all` is target. 
It thinks that `all` is not a target, but prerequisite.

```make
projects = someProject1 someProject2

push-all: $(addprefix push-,$(projects))

all: build-all push-all
```
(I skip some targets from example, push-someProject1 and push-someProject2 is generated targets)

**Comment by ylevin** [comment]
I found that workaround
```make
push-all: $(addprefix push-,$(projects))
	# this comment fix makefile plugin in Idea :)

all: build-all push-all
```

**Comment by singalen** [comment]
It's a known limitation that the plugin doesn't evaluate expressions.
The change above, BTW, adds a shell command to the target, even though it's just a comment.
This turns the rule from a pure dependency declaration (which a target can have many of) into target build rule, which must be only one.

**Comment by asm0dey** [comment]
It looks like to me that there is difference between "evaluate expressions" and "Mark expression as invalid". Maybe it's possible to add some exception to the parser?

**Comment by singalen** [comment]
Variables in `make` work as a pure text substitution, they literally can appear everywhere in the syntax.
It would be hard to describe a syntax every part of which has an exception for a variable. And then, what do we do when one variable generates a multiple syntax elements?

It would be easier (and more correct) to implement a parse-time static analysis that assigns values to a variables. Which is still a pretty huge project.
