### ISSUE TITLE
Ability to bypass broken inspections

### ISSUE THREAD

**Issue by oleg-rmd** [kropp/intellij-makefile#133]
Please add the ability to disable specific inspections (Preferences --> Editor --> Inspections), because right now a single incorrect/ broken inspection breaks highlighting and inspections for the rest of the file.

For example, this makefile works great as far as `make` is concerned, but the plugin gets confused on line  3 and stops working for all targets in the rest of the file.

![image](https://user-images.githubusercontent.com/50600269/74090150-20bea380-4a5d-11ea-8b52-407faf7e2d4c.png)

**Comment by singalen** [comment]
Nice idea. Might look like `#pragma MakefileSupport ignore-line`, or `ignore-target`.

**Comment by kropp** [comment]
Unfortunately, it's not an inspection failing, but parser.
Good thing is that parser is now much more accurate and recovers much better than before, so only the erroneous line will be highlighted.
