### ISSUE TITLE
Search target while typing in tool window

### ISSUE THREAD

**Issue by lordVNSH** [kropp/intellij-makefile#134]
Common features need to be supported on make tool window for better user experience. Example:
1. Search a target automatically while typing
2. Run a target with mouse double click

**Comment by singalen** [comment]
Please consider filing separate issues for separate feature requests.
Double-click where, by the way?

**Comment by lordVNSH** [comment]
Hey, sorry for the confusing request. I can create seperate feature requests for these if needed. Both the feature requests are for Make tool window (image attached). I want to run a target by double-clicking it and search a target by typing in this window. Similar to maven/ant/gradle tool windows.

![image](https://user-images.githubusercontent.com/24295749/75514228-fe48f600-5a1c-11ea-849a-cda7cd7ea6c7.png)

**Comment by kropp** [comment]
Double click is covered by #139
