### ISSUE TITLE
double clicking target in make tool window should do something

### ISSUE THREAD

**Issue by esuomi** [kropp/intellij-makefile#139]
Currently it seems that double clicking a target does nothing. Most probably a good action would be opening the relevant Makefile and autoscrolling to the row where the target is defined.

**Comment by lordVNSH** [comment]
Double clicking should ideally be running the target and not movnig to where it is defined (currently works with F4 key). This way it is also inline with the other tool window plugins like ant/maven

**Comment by esuomi** [comment]
That would be (even more) useful as well :)
