### ISSUE TITLE
No support for line breaks right after target name

### ISSUE THREAD

**Issue by Komzpa** [kropp/intellij-makefile#14]
![image](https://cloud.githubusercontent.com/assets/810638/22104819/1f92ae7c-de52-11e6-82e9-4127fc9883b7.png)

**Comment by Komzpa** [comment]
wonderful! just in case, the file from screenshot is at https://github.com/gojuno/make-profiler/blob/master/test/example.mk - sample Makefile for our recently opened make profiler :)

**Comment by kropp** [comment]
@Komzpa Thanks! Will take a look.
