### ISSUE TITLE
Feature: partial variable evaluation

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#145]
I've got a pretty complicated Makefiles with a lot of variables.
Their values are often only known in runtime, and are hard or impossible for the parser to deduce.

This hinders static code analysis, navigation, and other features, because `make`'s variables are more like C preprocessor macros than C variables.

Proposed solution.

a) Use constant values.
----

If a variable is assigned a constant value, use the value for the syntax analysis.

b) Evaluate constant expressions.
----
If a variable is assigned an expression that only refers to constant values, evaluate it and use the result for the syntax analysis.

c) Support variable overrides.
----
If a variable is `overridde`n, assign it this value and ignore all further assignment (unless it's `overridde`n again).

The case of `override` is particularly important. 

If I want to use the syntax analysis features, I can create and explicitly `-include .parser-hints.make` file with a contents like:
```
override MYVAR := actual value
```
and assign some variables by hand, using my knowledge of what the variable values will look like. This file could even be included automatically.

**Comment by singalen** [comment]
This will require a two-pass parsing, though: "preprocessor" and "final parsing".

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
