### ISSUE TITLE
.INTERMEDIATE not called

### ISSUE THREAD

**Issue by ruudk** [kropp/intellij-makefile#147]
```Makefile
start:
	docker run --rm --name=skipper \
		-v $(PWD)/routes.eskip:/routes.eskip \
		-p 9090:9090 \
		-p 9911:9911 \
		registry.opensource.zalan.do/pathfinder/skipper:latest \
		skipper -routes-file routes.eskip -application-log-level debug

stop:
	docker stop skipper

.INTERMEDIATE: stop
```

When I run `make start` it correctly calls `stop`. But when I run the `start` task in Jetbrains (GoLand) it doesn't call it.

**Comment by ruudk** [comment]
Maybe it's because when I click the Stop button, it kills the process immediately, instead of gracefully.
```
Process finished with exit code 9
```

**Comment by kropp** [comment]
`make` is now killed with SIGTERM instead of SIGKILL when Stop button pressed.

However, I must admit I wasn't able to reproduce this behavior on Ubuntu 19.10 with GNU Make 4.2.1

**Comment by ruudk** [comment]
@kropp Thanks for fixing this so fast. I think the SIGTERM would solve it. When do you tag a new release?

**Comment by kropp** [comment]
@ruudk Preview version is available https://plugins.jetbrains.com/plugin/9333-makefile-support/update/81904

**Comment by ruudk** [comment]
Tested it and it works!! Thanks 🎉
