### ISSUE TITLE
Analysis to find excess transitive dependencies

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#151]
```
a: b c
b: c
```
Here, `a: c` is excess, `a: b` and `b: c` is enough.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
