### ISSUE TITLE
stop doesn't send proper signals

### ISSUE THREAD

**Issue by TrentonAdams** [kropp/intellij-makefile#152]
I stopped the make run and it killed the make run itself, leaving the processes it ran.  When I press Ctrl-C from the CLI it sends the signal to the child process and it exits as well.  It would be nice if the plugin did something similar.  You could customize the type of signal it sends as well.

In my case, I'm using docker-compose, and if I want a quick exit I have to press Ctrl-C twice.  So, for that to work with the plugin it might be good if we could click the stop button twice to do the same thing.

**Comment by TrentonAdams** [comment]
For anyone happening upon this thread, I was able to make docker-compose operate a little nicer.  I was finding that I could go `docker-compose -> kill, down, then up`.  But, if I do that, the "up" takes awhile because it's still waiting for a complete removal of the containers before starting again.  So, I use parallelization...

First, pass the arguments `-j2` in the plugin run settings, this enables parallelization.

Now build tasks that allow for parallel jobs so that the kill/shutdown can occur while your build is occurring.
```
# run-no-rebuild is my building task, it does a bunch of stuff, including a `docker-compose build`
compose: composekill run-no-rebuild
	docker-compose up

composekill:
	docker-compose kill
	docker-compose down
```

**Comment by kropp** [comment]
Hey @TrentonAdams did you try plugin version 3.0 already? Should work better there.

**Comment by TrentonAdams** [comment]
Oh, I think I saw it working better and didn't know why.  I'll check again soon, not working today.

**Comment by TrentonAdams** [comment]
Confirmed, this behaves exactly the way that the CLI would behave.  Namely that you press stop, and if the process does not stop immediately it sits there without closing the IDEA task that's running.  If you hit stop again it sends Ctrl-C and kills the processes.
