### ISSUE TITLE
Escaping parentheses in shell function prompts an error in 3.0

### ISSUE THREAD

**Issue by PaperBag42** [kropp/intellij-makefile#155]
Hello, thanks for this plugin!
After updating to version 3.0, using a backslash to escape a parenthesis inside the shell function prompts an error.
For example:
```make
VUE_SRC=$(shell find ./src/ \( -name *.js -o -name *.vue \))
```
The `\(` prompts the error: `'!=', $, '+=', ',', ':', '::=', ':=', ';', <function name>, '=', '?=', chars, split, string or '|' expected, got '('`.
The `\)` also has a red underline but I don't see an error when I hover over it, so I'm not sure what that means.
Anyway, I hope this helps!

**Comment by singalen** [comment]
Wow, where do you get 3.0? Did you build it? I cannot see it even in the preview channel.

**Comment by PaperBag42** [comment]
@singalen LOL, I just installed the update in the plugin settings. It's in the stable channel: https://plugins.jetbrains.com/plugin/9333-makefile-support/versions
Is it not supposed to be there?

**Comment by singalen** [comment]
Oh, my bad. I am on the preview channel, in 2019 version, which will not have 3.0. Thanks.
