### ISSUE TITLE
Mixed eager and lazy assignments cause missed symbol references

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#158]
In this code:
```
A=C
A:=B
B=$(A)
C=Z
D=$(A)
```
selecting any of 4 `$(A)` variable references only highlights three of them.

Selecting the one in eager assignment (`:=`) misses the lazy one, and vice versa.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
