### ISSUE TITLE
Matching if/else/endif select a wrong endif

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#163]
I'm afraid regression happened and #122 no longer works correctly.

```
ifeq (1,2)

 ifeq (2,3)
  A := B
 else
  A := C
 endif

endif
```

Select the first `endif`, and it will be matched to the first `ifeq` instead of the last one. For some illustrations, see comments to #122.

This is the biggest issue for me now: I have a huge `if...else...endif` blocks, and I cannot rely on the plugin to correctly match `ifeq` and `endif`.

**Comment by kropp** [comment]
I've reverted the behavior, now only matching if/endif are highlighted. else keyword is never highlighted.
It seems that desired behavior is not supported by IntelliJ platform.

**Comment by singalen** [comment]
Thanks a lot!
I'm following the repo commits. Looks like you didn't push it 8)

**Comment by kropp** [comment]
Indeed. What I didn't forget though is to upload the plugin to the Plugin Marketplace.
