### ISSUE TITLE
PhpStorm Dracula theme strange green background

### ISSUE THREAD

**Issue by francescobianco** [kropp/intellij-makefile#164]
Please help me to change target script background color actually it placed to strange dark green.

![Screenshot from 2020-05-06 19-01-08](https://user-images.githubusercontent.com/472171/81206485-7824cf00-8fcc-11ea-90bc-a465efd2bc13.png)

**Comment by kropp** [comment]
See Settings | Editor | Color Scheme | General → Injected language fragment
