### ISSUE TITLE
parallel runs

### ISSUE THREAD

**Issue by TrentonAdams** [kropp/intellij-makefile#177]
Make supports parallelizing runs, this plugin does not.

```
parallel-run: task1 task2 task3
   do-something-else
```

Tasks that run linearly without parallelization...
```
parallel-and-linear-run: task1 | linear-task2 linear-task3
   do-something-else
```

To run them in parallel with up to 3 threads you'd use this from the CLI.
```
make parallel-run -j3
```

I pass -j3 in as arguments in the run configuration but that doesn't make it run in parallel.

I suspect if you just gave the option to pass "make" arguments, this would just work?

**Comment by singalen** [comment]
Just tried it, it worked for me.

```
all: test test2 test3

test:
	echo a
	sleep 1

test2:
	echo b
	sleep 1

test3:
	echo c
	sleep 1
```

`-j3` in "Arguments" of run configuration ran it in parallel.

**Comment by kropp** [comment]
Pipe symbol doesn't mean following tasks will run in parallel, see https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html for explanation.

@singalen's example runs just fine with `-j3` @TrentonAdams please check settings

**Comment by TrentonAdams** [comment]
> Pipe symbol doesn't mean following tasks will run in parallel, see https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html for explanation.
> 
> @singalen's example runs just fine with `-j3` @TrentonAdams please check settings

Correct.  Pipe symbol is for linear tasks

This is odd, I received a plugin update yesterday, I wonder if that affected it.  Cause I swear it wasn't working, but it is now.
