### ISSUE TITLE
run make task overwrites run-configuration

### ISSUE THREAD

**Issue by TrentonAdams** [kropp/intellij-makefile#181]
1. Create yourself a run configuration with special make arguments or environment variables.
2. Open the Makefile in your IDEA and click the run icon.
3. The run-configuration you created is completely wiped out.

This makes it very difficult to share run configurations with co-workers.

Before...
![image](https://user-images.githubusercontent.com/534192/89692794-ec238b80-d8c9-11ea-8a83-57fa567f828f.png)

After...
![image](https://user-images.githubusercontent.com/534192/89692830-fc3b6b00-d8c9-11ea-907c-b09a336e86be.png)

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
