### ISSUE TITLE
Not work after last update

### ISSUE THREAD

**Issue by klimby** [kropp/intellij-makefile#186]
After the last update (PHPStorm) all my run/debug configurations do not work. 

Makefile Example:

```
docker_bin := $(shell command -v docker 2> /dev/null)

ps:	## Docker ps
	@$(docker_bin)  ps
```

Terminal command `/usr/bin/make -f /home/klim/Nita/eks-project/e-server/cmd/Makefile ps` works fine.

Run|debug conf - does not work with error:

```
/usr/bin/make -f /home/klim/Nita/eks-project/e-server/cmd/Makefile ps
make: ps: Command not found
make: *** [ps] Error 127
/home/klim/Nita/eks-project/e-server/cmd/Makefile:7: recipe for target 'ps' fail

```

What am I doing wrong?

**Comment by canab** [comment]
The same (macOS)
Make process launched by the last CLion does not able to run any system program.
Output:
```
/usr/bin/make -f /path/to/Makefile update_common
make: which: Command not found
make: rm: No such file or directory
```

**Comment by EXHades** [comment]
* MACOS10.15.7
* Goland 2020.2.3  Build 202.7319.61
* Makefile support 3.5.1
* GNU Make 3.81

![image](https://user-images.githubusercontent.com/22260242/95990577-47d83b00-0e5e-11eb-9bbd-ab6b15036356.png)

Environment variables not load ?

![image](https://user-images.githubusercontent.com/22260242/95990545-3db63c80-0e5e-11eb-8744-4554500b9728.png)

**Comment by jordwest** [comment]
Same issue here on MacOS (Rider). It seems like it's started setting `PATH` to `null`. To confirm this, create a makefile with the following and set it up as a target with no environment variables set, but with "Include system environment variables" checked.

```make
build:
	echo "$(PATH)"
```

The makefile echos `null`. It's likely related to this change in the release notes:

```
Make runner now inherits customized environment variables in supported IDEs (e. g. in GoLand)
```

**Comment by madaxel** [comment]
I have the same issue.
Workaround in my case: 
Option 1: start from terminal using ```make build```
Option 2: rename my package.json in project root to package_.json (Which might be the cause)

Empting packae.json does not solve the problem.

**Comment by DannyHinshaw** [comment]
Can confirm this is also an issue in Webstorm for me running MacOS (Cataline v10.15.7).

Trying to run just about any command errors out. For example:

```makefile
test:
	which make
```

If I try to run this from the `Makefile` via the plugin I get:

```
/usr/bin/make -f /Users/dannyhinshaw/Desktop/Projects/project/Makefile test
which make
make: which: No such file or directory
make: *** [test] Error 1

Process finished with exit code 2
```

Per @jordwest suggestion I also run this for a test:

```makefile
build:
	echo "$(PATH)"
```

Running this from the Makefile via Plugin results in this:

```
/usr/bin/make -f /Users/dannyhinshaw/Desktop/Projects/project/Makefile build
echo "/Users/dannyhinshaw/Desktop/Projects/project/node_modules/.bin:null"
/Users/dannyhinshaw/Desktop/Projects/project/node_modules/.bin:null

Process finished with exit code 0
```

Also, this plugin is working just fine in Goland, last I checked at least. I can also run the commands in Webstorm terminal with no problems, the only time it errors is when using the play buttons via plugin.

**Comment by wadouk** [comment]
Downgrade the plugin to previous version ([3.5](https://plugins.jetbrains.com/plugin/9333-makefile-support/versions)) is a good workaround

**Comment by xinatcg** [comment]
same issue, and go back to 3.5

**Comment by xinatcg** [comment]
is it possible related to this fix? because someone said GoLand works but other Intellij apps do not work.

https://youtrack.jetbrains.com/issue/GO-6982

https://github.com/kropp/intellij-makefile/commit/dd4912203084ad94abcfde7def4c72040aab0c1f
