### ISSUE TITLE
Configure for use with windows WSL/Chocolatey install

### ISSUE THREAD

**Issue by chrisdonlan** [kropp/intellij-makefile#187]
I think this may be a usage question.  But I am a heavy make user working in a predominately windows-oriented shop, and that may be a rare enough occurrence that this is an issue. 

It is really important to make this workflow smooth, and I am attempting to configure the project to work on windows as well as linux.  

The makefile support plugin wants to call `/usr/bin/make`, but I need it to call simply `make` from windows, as `make` has been installed via `chocolatey` with the command `choco install make`.  

Is there a way to configure this path in pycharm?

**Comment by chrisdonlan** [comment]
I managed to get make to "work" in the sense that the binary executed via the following work-around:

1. open powershell
2. run the following to install and discover make's location:
```
PS>: choco install make
PS>: (get-command make).Path
```
3. open cmd as admin
4. run the following to link up the chocolatey `lib` and `bin` folders
```
C:\\> mkdir C:\\usr
C:\\> mklink /d C:\\usr\bin C:\\<insert-chocolatey-path-here>\bin
C:\\> mklink /d C:\\usr\lib C:\\<insert-chocolatey-path-here>\lib
```

Next, I clicked a plugin "play" button that runs `make -f C:\\...\...\makefile some-meta-rule`.  The meta rule calls some content windows cannot run, so I'll need to try some other things to make sure it is truly "not working".  However, the output suggests that something is going wrong prior to entering the directory and running the rule:

```
The system cannot find the path specified.
i was unexpected at this time.
The system cannot find the path specified.
``` 

There is no `i` anywhere in the rule chain.  But, I'll follow up with a Windows compatible rule test.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
