### ISSUE TITLE
Support Makefiles with different names

### ISSUE THREAD

**Issue by stefansjs** [kropp/intellij-makefile#189]
First of all, this plugin is great! I'm really happy to have makefile support in clion!

For clion, cmake generates makefiles named Makefile, but also, Makefile2. It would be great to either directly support cmake-generated makefile names, or to allow users to ender alternate filenames to run the plugin on!

Thanks!

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
