### ISSUE TITLE
Should not be able to click and run .PHONY

### ISSUE THREAD

**Issue by cbednarski** [kropp/intellij-makefile#19]
The clickable targets feature in 0.9 is great! Thanks for the hard work on this. I noticed that I can also click and run `.PHONY` targets, which are not actually targets.

![screen shot 2017-02-01 at 20 27 09](https://cloud.githubusercontent.com/assets/649798/22537164/edbb04ce-e8bc-11e6-805b-d42adcc9edd7.png)

[Explanation of PHONY](http://stackoverflow.com/questions/2145590/what-is-the-purpose-of-phony-in-a-makefile#2145605) if you haven't used it before.

Also big thanks for the hard tabs fix! This plugin is getting better all the time!

**Comment by jansenm** [comment]
And while you are there add the rest too :)

[Special Targets](https://www.gnu.org/software/make/manual/make.html#Special-Targets)

**Comment by jeckel** [comment]
:+1: 
And great work by the way :)

**Comment by kropp** [comment]
Thanks, guys!
Fixed. And I've added special syntax highlighting for special targets as well.

**Comment by cbednarski** [comment]
Working great, thanks again!
