### ISSUE TITLE
[Feature] add support for code folding regions

### ISSUE THREAD

**Issue by CircleCode** [kropp/intellij-makefile#192]
in big makefiles, it would be interesting to be able to define collapsible regions with the syntax already supported by IntelliJ:

```make
#region one
rule1:
  echo $@
#endregion
```

note1 : intelliJ  also supports closing sections with anything after the `endregion` comment, for example:

```make
#region one
rule1:
  echo $@
#endregion one
```
note2: nested sections are allowed

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
