### ISSUE TITLE
Editor tab title sometimes loses its directory prefix

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#195]
Editor tabs have an option - "Show directory for non-unique file names".
Sometimes, only sometimes, Makefiles do not have this prefix.
I once reported this issue to Jetbrains: https://youtrack.jetbrains.com/issue/IDEA-207343, and they didn't find it in the core. Could it be the plugin?
![Screen Shot 2020-12-01 at 10 42 54 AM](https://user-images.githubusercontent.com/151199/100783482-ae8bc680-33c2-11eb-92c4-01a162bec6a5.png)

**Comment by singalen** [comment]
My project was still indexing, maybe it has something to do with it.
After the indexing was done, the tabs got their prefixes.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
