### ISSUE TITLE
Shell syntax in $(shell) function and backslash

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#197]
This produces an error:
```
A = $(shell date +\"%Y%m%d%H%M%S\")
```
`<lexem list> expected, got \`.
Is this a problem with Make syntax trying to parse and pre-process a shell command, or with the injected shell language?

**Comment by singalen** [comment]
Another possibly related problem:
```
$(shell if [ -d ddd ]; then echo "yes"; else echo "No"; fi)
```
The plugin tries to parse `else` as `make` syntax.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
