### ISSUE TITLE
Functions and targets defined in included files are not recognized nor autocompleted

### ISSUE THREAD

**Issue by rrajkomar** [kropp/intellij-makefile#199]
Any function defined in an included mk file using define is not autocompleted in a `$(call [function_name])` call in the IDE.
Same goes for targets that are defined in an included mk file

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
