### ISSUE TITLE
Working directory is project root instead of makefile path

### ISSUE THREAD

**Issue by jeckel** [kropp/intellij-makefile#22]
Hi, thanks for fixing so quickly #19 and #20 .

I have another feature request. I have a makefile in a subdirectory of my project. When running a target, it seems that it's running in the project root folder as a working directory instead of the Makefile directory.

For example, this will always display the project root, and not the makefile directory
```Makefile
default:
    @echo `pwd`
```

**Comment by kropp** [comment]
This makes sense, thanks!
