### ISSUE TITLE
support shebang for choosing make

### ISSUE THREAD

**Issue by Komzpa** [kropp/intellij-makefile#24]
Thanks a lot for the 'run' button!

We're using https://github.com/gojuno/make-profiler to run our Makefiles to get idea of how long the target was executing.

It looks like integration of it can be seamless if we put `#!/usr/bin/env profile_make` at the start of Makefile. Can it be supported for choosing the correct Make executable?

**Comment by kropp** [comment]
You can set custom `make` command in Settings → Build, Execution, Deployment → Make
Does it work for you?

**Comment by Komzpa** [comment]
this does solve my use case, thanks.

**Comment by kropp** [comment]
I close this issue then, feel free to reopen it if there are any other unsupported use cases.
