### ISSUE TITLE
.PHONY: lines are considered as commands

### ISSUE THREAD

**Issue by andreif** [kropp/intellij-makefile#32]
I am not sure if they should be:

<img src="http://i.imgur.com/eFPzvyH.png" width="250">

**Comment by kropp** [comment]
It is fixed in 1.0 released yesterday, please update plugin and check again.

**Comment by andreif** [comment]
@kropp No, it's not 😄 I am using 1.0.
*(sorry for not mentioning it, thought it happens for everybody)*

**Comment by kropp** [comment]
You are right, somehow I missed it.
