### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by andreif** [kropp/intellij-makefile#40]
It would be great if there were build instructions in readme to allow testing the latest changes before they are released. I see some syntax errors but they may be already fixed in master so I am not sure if I should report them or just wait for the next release.

I found the plugin jar, but not sure how to produce a new one and what dependencies are required.
```
$ ls -l ~/Library/Application\ Support/PyCharm2016.3/intellij-makefile/lib/
total 336
-rw-r--r--  1 andrei  staff   165K Feb 24 09:44 intellij-makefile-1.0.jar
```

**Comment by kropp** [comment]
Sorry for the late answer. I've added some instructions to Readme. If you have any questions, don't hesitate to ask me. Will do my best to answer faster :)
