### ISSUE TITLE
Recognize Special Targets

### ISSUE THREAD

**Issue by Fleshgrinder** [kropp/intellij-makefile#48]
Magic targets are currently grayed out and reported as _redundant rules_. It would be great if the plug-in recognizes the magic targets and displays them either normally or with a special color.

https://www.gnu.org/software/make/manual/html_node/Special-Targets.html#Special-Targets

Note that some of the special targets require an argument to be effective, e.g. `.PHONY`.

**Comment by kropp** [comment]
Thanks for a feedback, looks like I already fixed this in master, will release an update ASAP.
