### ISSUE TITLE
Error: NoClassDefFoundError

### ISSUE THREAD

**Issue by catvec** [kropp/intellij-makefile#49]
I have a Makefile and Vim plugin. Intelijj Info:

```
IntelliJ IDEA 2017.1.4
Build #IU-171.4694.23, built on June 6, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.11.6-1-ARCH
```

Steps to reproduce:

1. Went to edit a Makefile
2. Navigated my cursor the the correct line
3. Typed "A" (Vim insert at end of line)
4. And Intelijj errored

Unable to edit any text in the Makefile. I tried opening and closing the file several times. I am however able to edit other files.
 
[Stack trace](https://pastebin.com/raw/5QWJmhxG)

**Comment by kropp** [comment]
I cannot reproduce this issue. If it persists, please check you have all latest plugin versions installed and post full exception stacktrace here.

**Comment by catvec** [comment]
I realized it was probably a very rare bug, thought I'd report just so that
class got a nice once over in case the issue was obvious.
