### ISSUE TITLE
Incompatible with builds > 163

### ISSUE THREAD

**Issue by mikemand** [kropp/intellij-makefile#5]
I'm using PhpStorm EAP 2017.1 (build 171.1834.12), is there any way you could make this plugin compatible?

PhpStorm 2017.1 EAP
Build #PS-171.1834.12, built on December 22, 2016
JRE: 1.8.0_112-release-b620 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by kropp** [comment]
I've uploaded version 0.5.1 compatible with 2017.1 EAP.

**Comment by mikemand** [comment]
Thank you!
