### ISSUE TITLE
Force indent style to tabs

### ISSUE THREAD

**Issue by ulope** [kropp/intellij-makefile#50]
Currently editing makefiles uses the IDE default indentation setting. This breaks when this is set to spaces. The plugin should force the indentation style to tabs in makefiles.

**Comment by kropp** [comment]
It already does.
Could you please check you are using the latest version and if so, please send me a sample file and steps to reproduce the incorrect behavior.
Thank you!

**Comment by ulope** [comment]
I'm using version 1.2 from the repository.

There are no special circumstances. Create or open any makefile and type away.
I've made a screen recording:
![](https://ds.ulo.pe/fE4Vp7ICwl.gif)

**Comment by techdragon** [comment]
I experience the same behaviour in Pycharm.

**Comment by bruderstein** [comment]
I just had the same thing, and I found it was the filetype wasn't correctly assigned.

Preferences, Editor, File types
Then find `GNU Make`
Registered Patterns included `Makefile.*` and `makefile` but not `Makefile`. When I added `Makefile` it said `Makefile` was already registered to the type `Makefile` (which doesn't exist in my list of registered file types), I clicked to replace it and now it works - I get tab support and proper highlighting.

**Comment by kropp** [comment]
Thanks for update! This explains why I wasn't able to reproduce this issue
Will investigate it further

**Comment by dylanPowers** [comment]
For me, on 2018.1 Ultimate, I had the same behavior as bruderstein with the filetype not getting correctly assigned. After reassigning the pattern "Makefile" to "GNU Make", and purging any possible conflicting settings, I had to uninstall the plugin and then re-install it to get tabs working correctly. A simple restart wasn't sufficient.

**Comment by singalen** [comment]
Having the same problem on 1.5/CLion, and have had it for quite some time.

The file type is assigned correctly, I can see run buttons on the gutter.

If you press Return after a line with existing tab, it's fine. If there were tabs in the file any time before, it will work. But if it's a completely new `Makefile`, it will insert spaces.

**Comment by kpe** [comment]
after installing the plugin in pycharm, I'am not able to enter tabs in a Makefile - pressing tab results in nothing. This way writing new make rules is impossible.  Even having correct rules (i.e. with tabs) doesn't help. I have to copy a tab from a previous rule to enter new rules.

**Comment by ulope** [comment]
I found the source of my problem:
The project in question contains an `.editorconfig` file and I also have the support plugin installed.
Since the `.editorconfig` file had
```
[*]
indent_style = space
indent_size = 4
```

This took precedence over the makefile plugin.

Adding 
```
[Makefile]
indent_style = tab
```

To `.editorconfig` fixed the problem.

**Comment by kpe** [comment]
sadly, neither disabling the `EditorConfig` plugin nor editing `.editorconfig` makes a change in my case.

**Comment by kropp** [comment]
Added code style settings with forced tabbed indentation.
