### ISSUE TITLE
Makefile tool window

### ISSUE THREAD

**Issue by dlsniper** [kropp/intellij-makefile#54]
Original issue at: https://youtrack.jetbrains.com/issue/GO-4331 by @alexcarruthers

Similar to how npm tasks are coalesced into a tool window in WebStorm, having a tool window for makefiles would be beneficial. There's a 3rd party plugin that puts play buttons next to tasks in the file itself, but that requires opening the file, clicking the button, etc... Having the ability to have all the commands just there to be used would be beneficial

**Comment by kropp** [comment]
Nice idea, thanks!
Right now, one can run tasks from File Hierarchy tool window, but of course it is only available for currently opened file.

**Comment by kropp** [comment]
Implemented in 1.5
