### ISSUE TITLE
Setting make options like -j 8

### ISSUE THREAD

**Issue by Viatorus** [kropp/intellij-makefile#58]
First, thank you for this great tool.

How can I set command line options for make?

**Comment by kropp** [comment]
Thanks!
I added such an option in the next version.

**Comment by Andy-Richards** [comment]
As this is issue is closed does it mean that this feature is in the current release version?

Many thanks.

**Comment by kropp** [comment]
@Andy-Richards no, it's not yet released. Will try to push an update before the end of the year.
