### ISSUE TITLE
Grammar incorrect for multi-branch conditionals

### ISSUE THREAD

**Issue by RMMoreton** [kropp/intellij-makefile#60]
According to the GNU `make` manual (found [here](https://www.gnu.org/software/make/manual/make.html#Syntax-of-Conditionals)), the following Makefile is valid:
```
foo: foo.c
ifeq ($(DEBUG),TRUE)
	cc -g -o foo foo.c
else ifeq ($(DEBUG),FALSE)
	cc -o foo foo.c
else
	@echo "Please set DEBUG to TRUE or FALSE."
endif

clean:
	- rm -f foo
```
With a simple `foo.c` file, `make` runs perfectly well using this Makefile. However, this Intellij plugin marks a syntax error at the `clean` target.

I believe the problem is with the grammar. Specifically, in grammars/Makefile.bnf, I saw the lines
```
conditional ::= conditional-keyword condition branch ('else' branch)* 'endif'
...
branch ::= (conditional|command|variable-assignment)*
```
Reading those, it seems to me that this tool expects my `else ifeq` block to be closed by it's own `endif` statement. That led me to try the following Makefile:
```
foo: foo.c
ifeq ($(DEBUG),TRUE)
	cc -g -o foo foo.c
else ifeq ($(DEBUG),FALSE)
	cc -o foo foo.c
endif
else
	@echo "Please set DEBUG to TRUE or FALSE."
endif

clean:
	- rm -f foo
```
This file is correctly highlighted, with no syntax errors reported. However, running `make` reports
```
Makefile:7: *** extraneous 'else'.  Stop.
```

**Comment by kropp** [comment]
Thanks for bug report! Fixed.
Actually there are many ways to write complex conditionals, see for example https://github.com/ioquake/ioq3/blob/master/Makefile
