### ISSUE TITLE
Does not support $(error <shell command>) in between ifeq

### ISSUE THREAD

**Issue by wheelerlaw** [kropp/intellij-makefile#66]
See image:
![image](https://user-images.githubusercontent.com/3081566/36132755-050141d6-1047-11e8-8ad9-0dd04ae7ac3e.png)

Tooltip:
![image](https://user-images.githubusercontent.com/3081566/36132778-2b4cd1ca-1047-11e8-897e-d516392bb8e5.png)

Make runs as expected when I run it from the terminal, producing `Makefile:9: *** Go is not installed.  Stop.` as output.

**Comment by wheelerlaw** [comment]
Sorry for the noise, hit the close button by mistake.

**Comment by SamirTalwar** [comment]
This is also true for `ifneq`, `ifdef` and `ifndef`.
