### ISSUE TITLE
False syntax error for target starting with @

### ISSUE THREAD

**Issue by fahrradflucht** [kropp/intellij-makefile#69]
On makefiles with a target name starting with an `@` the plugin reports `':', '::' or <target> expected, got ''` and completely stops working for the reset of the file.

Make doesn't care about targets starting with an `@` sign though and works like normal.

**Comment by kropp** [comment]
Cannot reproduce this bug. Could you please provide an example?

**Comment by fahrradflucht** [comment]
Thanks for looking into this. There is another thing that is necessary which I didn't notice before to get the error: Both the target and a pre-requisite must start with an @-sign.

Repro:
```Makefile
@example/lib:
	echo "build lib"

@example/build: @example/lib
	echo "build app"
```

**Comment by kropp** [comment]
Thanks, now I can reproduce it!
