### ISSUE TITLE
Execute target & Structure view broken on IDEA 2018.1.4

### ISSUE THREAD

**Issue by markmandel** [kropp/intellij-makefile#70]
IntelliJ IDEA 2018.1.4 (Ultimate Edition)
Build #IU-181.5087.20, built on May 16, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.9.0-6-amd64

Since updating, I can no longer execute a target (the nice green arrow next to each Make target is gone), and the Structure pane is empty (whereas before it used to list all the targets).

**Comment by kropp** [comment]
Fixed via dfdc63a5cdfcf81d145d752a1a63306c8d2c716f
