### ISSUE TITLE
run make inside virtualenv?

### ISSUE THREAD

**Issue by jas-ho** [kropp/intellij-makefile#74]
The active PyCharm-project is associated with a virtualenv. Hence, when I open a terminal I'm dropped into bash with the virtualenv activated. Inside this terminal I can do `make my_target` and it works.

If I click on the "play"-icon next to my_target however, it **fails because it is executed in a shell which does not activate the virtualenv**. Any suggestion how to make "make" run in bash inside the virtualenv when hitting play?

Thanks a lot for your help!

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
