### ISSUE TITLE
Some of functions are not supported

### ISSUE THREAD

**Issue by kunyavskiy** [kropp/intellij-makefile#75]
Using of eval, call, foreach functions break everything including code highlighting.

Probably, they can be parsed in grammar, even if not proceed by plugin.

Full list of functions can be found here:
https://www.gnu.org/software/make/manual/html_node/Functions.html

I can do it myself in couple weeks. What format of pull requesting you like?

**Comment by kropp** [comment]
Here is an example commit which added support for some other functions: c3cb4db14921dd0aa2909feb5840933b79ba513e

If you want to contribute you'll need to update parser and lexer, regenerate them (see README.md) and add a test.

**Comment by kunyavskiy** [comment]
I have started some work here https://github.com/kunyavskiy/intellij-makefile/commits/fixes. 

But I noticed a big problem. which will probably need big parsing rewriting to fix. 

For example code like this which is quite usefull can't be parsed by current lexer even if support foreach and call functions.
```
$(foreach file, ${FILE_LIST}, $(call MyMacro, ${file}))
```

To fix this one will need get rid of FUNCTION state in lexer, because otherwise he will need to check balanced brackets sequence using automaton, which is impossible. 

Probably, it can be done, because this state is quite useless anyway, but it is bigger work than I thought first. 

Also this will help to parse something like `${C_FILES_LIST:%.c=${OBJECTS_DIR}/%.o}`
which is not parsed either now.

**Comment by kropp** [comment]
Yeah, I see. Current lexer impl is a bit hacky and dirty. Seems it's time to rewrite it.

Parsing function calls and variables correctly will also allow to implement completion in appropriate places.

**Comment by johanLsp** [comment]
Having a simple support of functions as @kunyavskiy started in [Add full list of makefile functions](https://github.com/kunyavskiy/intellij-makefile/commit/c082be088529702a4c26f3b94fd77777beb243e5) would already be a great improvement and should't require too much effort. 
The lexer should easily be able to support non-nested functions such as:
`$(call locate_lib, $(lib_name))`.
