### ISSUE TITLE
Run command doesn't work with variable in target name

### ISSUE THREAD

**Issue by kunyavskiy** [kropp/intellij-makefile#76]
If there is a variable in target name something like

EXE := objs/bin
${EXE}/my-binary: 
   some command here

run button near this target doesn't work because it tries to run make ${EXE}/my-binary, not run objs/bin/my-binary.

**Comment by kunyavskiy** [comment]
Probably, that can be fixed by some parsing of make -p output, but I'm not sure how to exacltly.

**Comment by kropp** [comment]
`make -np -f path/to/Makefile` resolves all variables, so it can indeed help to evaluate such rules correctly.

**Comment by kunyavskiy** [comment]
You can have a problem with variables, that are set several times. But probably, in most cases it will work. 

Also, there can be a problem, when there is root makefile, which includes others, and the rule is in small one. Because you need to evaluate with -f marked for full one, to get variable values.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
