### ISSUE TITLE
Support .RECIPEPREFIX so we can use spaces instead of tabs

### ISSUE THREAD

**Issue by nitrocode** [kropp/intellij-makefile#77]
First of all thank you so much for this plugin. It makes modifying `Makefile`s so much easier.

The new GNU Make 4.1 supports a variable called `.RECIPEPREFIX` which allows us to use spaces instead of tabs. I noticed when I used this variable that the plugin didn't recognize it and still discolored areas where 4 spaces instead of a tab was detected.

> * New special variable: .RECIPEPREFIX allows you to reset the recipe introduction character from the default (TAB) to something else.  The first character of this variable value is the new recipe introduction character.  If the variable is set to the empty string, TAB is used again. It can be set and reset at will; recipes will use the value active when they were first parsed.  To detect this feature check the value of $(.RECIPEPREFIX).

^ From [2010 mailing list](https://lists.gnu.org/archive/html/make-alpha/2010-07/msg00025.html)

> This does it for me if you would like to use spaces
> `.RECIPEPREFIX +=`
> [Example](https://github.com/svnpenn/glade/blob/9e1a1bb/ffmpeg/makefile#L1)

^ From [stackoverflow](https://stackoverflow.com/a/26200436)

If on a mac, you might have the old version installed which doesn't support it... so you can install gnu make instead or `gmake`

```
$ make --version | head -1
GNU Make 3.81
$ brew install homebrew/core/make
...
$ gmake --version | head -1
GNU Make 4.2.1
```

^ From [apple.stackexchange.com](https://apple.stackexchange.com/a/261948)

**Comment by kropp** [comment]
Great suggestion, thanks! It will require significant rework though. I need some time to think about it.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
