### ISSUE TITLE
Unresolved Prerequisite when using include'd Makefiles

### ISSUE THREAD

**Issue by tebriel** [kropp/intellij-makefile#78]
We have a number of common functions shared in a file named `Makefile.common`. At the top of each makefile, we do the following:

### Makefile.common
```
some_target:
    echo "burritos"
```

### Individual Service Makefile
```
include ../Makefile.common

a_thing: some_target
    echo "tacos"
```

The Makefile linter is warning me that `some_target` in this case is an `Unresolved prerequisite`. Can we get the linter to follow the `include`s and resolve those as well?
Thanks!

**Comment by kropp** [comment]
Related to #76 
As suggested in that issue, implementing a linter which calls `make` to resolve all targets and variables should help

**Comment by hannes-ucsc** [comment]
This would be really nice to have. Most non-trivial GNU make Makefiles use includes. And I don't think this is related to #76. The Makefile parser just needs to read the included Makefiles as if their contents appeared verbatim in place of the `include` directive.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
