### ISSUE TITLE
Executable is not debuggable from the plugin template or from an application. 

### ISSUE THREAD

**Issue by jwmurray** [kropp/intellij-makefile#79]
Plugin works perfectly to allow for making Makefile targets.  I am having trouble debugging the executables that are created from the Makefile.  Could you provide information on how to do that?  I do not see an executable field in the Makefile template.  Also, if I try to create an application that points at the created executable, Clion responds that it is not able to run on '<default>'.  Any help would be much appreciated.

I am sure this is just a documentation issue.  I hope you could assist in understanding how to set up and debug the created executables.

**Comment by kropp** [comment]
This is out of scope of the Makefile plugin. It only provides means to run Makefile targets and doesn't care about their outputs.

I'd suggest I should create Run Configuration of type "Application" in CLion and set up correct executable there.

**Comment by socketbox** [comment]
@jwmurray I'm in the same boat. It seems that CLion is tightly coupled to the notion of each project having a CMake file and configuration. I cannot find a way to run and debug the simplest of C applications.
