### ISSUE TITLE
tab before comment breaks formatting

### ISSUE THREAD

**Issue by Komzpa** [kropp/intellij-makefile#8]
![tab-before-comment](https://cloud.githubusercontent.com/assets/810638/21768932/3114620c-d68d-11e6-8d8e-29f54259e620.gif)

**Comment by kropp** [comment]
Fixed. Thanks a lot for submitting bugs!

**Comment by Komzpa** [comment]
Thanks a lot for fixing them so fast, and for such a great thing that colorizes half of my data processing pipeline ;)
