### ISSUE TITLE
"Makefile" replaced by "Makefile.*"

### ISSUE THREAD

**Issue by K4zuki** [kropp/intellij-makefile#83]
Hello,
I am happy to use this plugin, it is really helpful, but facing a little problem.

### Conditions

- PyCharm Professional 2018.2.4
- MacOS

### How to reproduce

- Remove all items from "Registered patterns" list for GNUmakefile
- add simple `Makefile` to the list. No`*` nor `?`
- Apply change
- (IDE seems to start index filesystem - wait to finish it)
- Restart IDE

### Problem

- `Makefile` disappears and `Makefile.*` appears in same list

**Comment by kropp** [comment]
The way how file types are registered has been reworked recently (both in platform and plugin) and the issue doesn't reproduce with the latest versions.
