### ISSUE TITLE
Run make on a remote host

### ISSUE THREAD

**Issue by nCrazed** [kropp/intellij-makefile#85]
I have a development environment managed by vagrant and some of the make targets need to run in that environment. I'd like to have at least a way to run make over SSH with custom port and path to private key.

Implementation for this is likely to overlap with #74

**Comment by RPCMoritz** [comment]
This would probably also help with #73

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
