### ISSUE TITLE
[Uber-feature] debugger support with remake

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#89]
There exists a version of `make` with a built-in debugger: [remake](http://bashdb.sourceforge.net/remake/).

It would be fantastic to have IDEA support debugging Makefiles.

It may be worth bundling `remake` with CLion's toolchain for this purpose.

**Comment by singalen** [comment]
[Unit tests](https://sourceforge.net/projects/munit/) support is probably a different feature.

**Comment by kropp** [comment]
You can set up any executable in **Settings → Build, Execution, Deployment → Build tools → Make** as long as it supports same command line parameters

**Comment by singalen** [comment]
Thanks, that I did.

The key word here is "debugger". Like in debugging things in IDE, setting breakpoints, watching variables, evaluating expressions. `remake` does that; in other senses, it's a drop-in replacement for `make`. That's why I referenced it, not because I cannot set up an executable alias.

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
