### ISSUE TITLE
[Feature] Support language injection (default to bash/ash)

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#90]
With a [language injection](https://www.jetbrains.com/help/clion/2019.1/using-language-injections.html) added to CLion 2019, it makes even more sense to support it in Makefiles.

Most of Makefiles are written in `bash` or POSIX `sh`. It would be awesome if the plugin used <strike>[BashSupport](https://github.com/BashSupport/BashSupport)</strike> [Shell Script bundled plugin](https://www.jetbrains.com/help/idea/shell-scripts.html) for an injected language. 

Support for changing the injection language with a comment would be nice to have too.

**Comment by techdragon** [comment]
Language injection does appear to work, but not where/how it is needed. 😦 

I can inject a language after the start of a comment, or inside a comment... but not inside of a variable definition, so it cant be used to syntax highlight a script embedded as a variable.

Edit: It seems like language injection is currently limited to single line comments. I cant trick it into doing anything else. And I wasn't able to work out how to create them, the Injection information is missing from the JetBrains plugin SDK's custom language section 😦

**Comment by singalen** [comment]
After another half a year with Makefiles, I would say this is the feature I need the most, even more than a correct Makefile parser - the combined `Makefile` and `sh` syntax highlight/checking/aids.

More specifically, ["Shell Script"](https://www.jetbrains.com/help/idea/shell-scripts.html) bundled plugin should be used as an injected language by default in every line of makefile rules, and in `$(shell )` function.

This might need to be optional, as some rare Makefiles are Windows-based.
