### ISSUE TITLE
Debug action does nothing if there is "Before launch" set to Makefile Run Configuration

### ISSUE THREAD

**Issue by Elizaveta239** [kropp/intellij-makefile#92]
Reported by user: 
https://youtrack.jetbrains.com/issue/PY-33697

What steps will reproduce the problem?

- Create any Run configuration (tested with Python and JavaScript run configurations)
- Create Makefile Run configuration
- In the first Run configuration set: Before launch -> Run Another Configuration -> select second configuration

Run first Run configuration -> works fine
Debug first Run configuration -> nothing happens

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
