### ISSUE TITLE
Feature to run outputted executable

### ISSUE THREAD

**Issue by Ge0rges** [kropp/intellij-makefile#94]
CLion really dropped the ball on makefile support. It would be great if additionally to running makefiles, this plugin could help bridge the gap to run the resulting binary executable and debugging it.

**Comment by singalen** [comment]
In their defense, a) they are working on it, and b) Makefiles are really a horrible format for project configuration, because they are frequently cross-bred with arbitrary bash scripts.
I believe you can work around it by adding external tool to run configuration template.

**Comment by kropp** [comment]
According to CLion roadmap they are working on native Makefiles support, see https://blog.jetbrains.com/clion/2019/12/clion-2020-1-roadmap/

It is impossible to correctly detect what "outputted executable" is. I'd second @singalen's suggestion and suggest to add a run configuration manually.
