### ISSUE TITLE
Freeze in CLion 2019.1 EAP

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#95]
I reported a freeze in Youtrack ([CPP-15401](https://youtrack.jetbrains.com/issue/CPP-15401#)) and they believe it's a intellij-makefile problem.
[threadDumps-freeze-20190210-103219-CL-191.4738.15-71sec.zip](https://github.com/kropp/intellij-makefile/files/2852469/threadDumps-freeze-20190210-103219-CL-191.4738.15-71sec.zip)
[threadDumps-freeze-20190210-103517-CL-191.4738.15-25sec.zip](https://github.com/kropp/intellij-makefile/files/2852470/threadDumps-freeze-20190210-103517-CL-191.4738.15-25sec.zip)

**Comment by maxim-banaev** [comment]
Duplicated in CLion tracker: https://youtrack.jetbrains.com/issue/CPP-15401
