### ISSUE TITLE
Highlighting isn't working as expected

### ISSUE THREAD

**Issue by wotta** [kropp/intellij-makefile#98]
Could we can the same highlighting options that sublime text allows us to have in phpstorm for this plugin?

Sublime text also highligts bash commands where phpstorm doesn't.

In sublime text i have the following highlighting:
![sublime](https://puu.sh/CSuDu/b0743f93d7.png)

And in phpstorm i have the following:
![phpstorm](https://puu.sh/CSuFW/dae24d9725.png)

**Comment by kropp** [comment]
Please see #90
